In [1]:
#@title Colab setup and imports

import jax
from jax import numpy as jp
from matplotlib.lines import Line2D
from matplotlib.patches import Circle
import matplotlib.pyplot as plt


import brax



/home/mohsen/anaconda3/envs/ray2.2/lib/python3.8/site-packages/flax/struct.py:132: FutureWarning: jax.tree_util.register_keypaths is deprecated, and will be removed in a future release. Please use `register_pytree_with_keys()` instead.
  jax.tree_util.register_keypaths(data_clz, keypaths)
/home/mohsen/anaconda3/envs/ray2.2/lib/python3.8/site-packages/flax/struct.py:132: FutureWarning: jax.tree_util.register_keypaths is deprecated, and will be removed in a future release. Please use `register_pytree_with_keys()` instead.
  jax.tree_util.register_keypaths(data_clz, keypaths)


In [3]:
def coordinate_transform(point, grid_map_shape):
    return 2. * (grid_map_shape[1] * point[0] + point[1]) / (
        grid_map_shape[0] * grid_map_shape[1]) - 1.

In [11]:
embedding_dim = 4
size0 = (11, 11)
corridor0 = (1,3)
config0 = {'size': size0,
                        'corridor': corridor0,
                        'region': {0: (1, 1), 1: (9, 9)}}

flatten(config0)

# points = [(i, j) for i, j in itertools.product(range(1, 10), range(1, 4))] + [(i, j) for i, j in itertools.product(range(1, 10), range(7, 10))]
# points_compact = [(i, j) for i, j in itertools.product(range(1, 10), range(1, 7))]
# # embedding_map = [{0: (i, j), 1: (9, 9)} for i, j in itertools.product(range(1, 10), range(1, 4))] + \
# #                 [{0: (i, j), 1: (9, 9)} for i, j in itertools.product(range(1, 5), range(7, 10))] # LR destination maps
# 
# 
# 
# embedding_map = [{0: (1,1 ), 1: finish} for finish in points if finish != (1,1)]
#                 # [{0: start, 1: (1,1)} for start in points if start != (1,1)]
# # embedding_map_compact = [{0: start, 1: (9, 6)} for start in points_compact if start != (9, 6)] + \
# #                 [{0: start, 1: (1, 1)} for start in points_compact if start != (1, 1)]
# 
# embedding_transform = [np.array([coordinate_transform(v[0], size0), coordinate_transform(v[1], size0)]) for v in
#                        embedding_map]
# 
# # embeddings = np.random.randn(len(embedding_map), embedding_dim)
# embeddings = np.array([[2 * v[0][0] / size0[0] - 1, 2 * v[0][1] / size0[1] - 1, 2 * v[1][0] / size0[0] - 1, 2 * v[1][1] / size0[1] - 1] for v in
#                        embedding_map], dtype=np.float64)

{('size',): (11, 11),
 ('corridor',): (1, 3),
 ('region', 0): (1, 1),
 ('region', 1): (9, 9)}

In [8]:
embeddings

array([[-0.81818182, -0.81818182,  0.63636364,  0.09090909],
       [-0.81818182, -0.63636364,  0.63636364,  0.09090909],
       [-0.81818182, -0.45454545,  0.63636364,  0.09090909],
       [-0.81818182, -0.27272727,  0.63636364,  0.09090909],
       [-0.81818182, -0.09090909,  0.63636364,  0.09090909],
       [-0.81818182,  0.09090909,  0.63636364,  0.09090909],
       [-0.63636364, -0.81818182,  0.63636364,  0.09090909],
       [-0.63636364, -0.63636364,  0.63636364,  0.09090909],
       [-0.63636364, -0.45454545,  0.63636364,  0.09090909],
       [-0.63636364, -0.27272727,  0.63636364,  0.09090909],
       [-0.63636364, -0.09090909,  0.63636364,  0.09090909],
       [-0.63636364,  0.09090909,  0.63636364,  0.09090909],
       [-0.45454545, -0.81818182,  0.63636364,  0.09090909],
       [-0.45454545, -0.63636364,  0.63636364,  0.09090909],
       [-0.45454545, -0.45454545,  0.63636364,  0.09090909],
       [-0.45454545, -0.27272727,  0.63636364,  0.09090909],
       [-0.45454545, -0.

In [14]:
def box2discrete( val, grid_map_shape):
    return tuple(np.round(divmod((val +1)*grid_map_shape[0]*grid_map_shape[1]/2, grid_map_shape[1])).astype(int))

In [27]:
def coordinate_transform(point, grid_map_shape):
    return 2. * (grid_map_shape[1] * point[0] + point[1]) / (
        grid_map_shape[0] * grid_map_shape[1] -1 ) - 1.

In [31]:
map_shape = (5, 11)

points = [(i,j) for i , j in itertools.product(range(0, map_shape[0]), range(0, map_shape[1]))]
point_idx = [p[0]*map_shape[1]+ p[1] for p in points]
print(coordinate_transform((2, 5), map_shape))

0.0


In [32]:
s, d, D, l, x = symbols('s d D l x')


equation = Eq(d*(1-s)/((1+x)*s) + d*(s*(x+1))/(s*x+1) + s* l/(1+ (s*x**2 + x)/(1+x)), 2*D + d)


In [33]:
sols = solve(equation, x)


KeyboardInterrupt



In [35]:
a = np.array([1, 3])
b = np.array([5, 7])
a/(b-1)

array([0.25, 0.5 ])

In [76]:
g1, g2, m, P, D, V, m0, m_t, s0, S, U= symbols('g1 g2 m P D V m0 m_t S s0 U')


equation = [(1+s0*g2)*m -( m_t - g1*s0*U + s0*g2*m0),
             (m_t - m0 - g1*s0* U)*S*(m_t - m0 - g1*s0* U)/(1+s0*g2) - 2*D/s0,
             P - V + (s0/(1+ s0*g2))*(m_t - m0 - g1 *s0 *U)*S*U,]


In [77]:
sols = solve(equation, m, g1, g2)

In [79]:
sols[0][0]

(-P + S*U*m0*s0 + V)/(S*U*s0)

In [80]:
sols[0][1]

(2*D*U - P*m0 + P*m_t + V*m0 - V*m_t)/(S*U*(P - V))

In [81]:
sols[0][2]

(2*D*S*U**2*s0 - P**2 + 2*P*V - V**2)/(S*(P**2 - 2*P*V + V**2))

In [5]:
import sympy 
g1, g2, P, D, V,   s0= sympy.symbols('g1 g2  P D V s0')
e, V= sympy.symbols('e V')

# S = MatrixSymbol('S', 2, 2)
mu = sympy.MatrixSymbol('mu', 1, 4)
u = sympy.MatrixSymbol('u', 1, 4)
W = sympy.MatrixSymbol('W', 4, 4)
# m = MatrixSymbol('m', 1, 2)
#
# eqns = [(1+s0*g2)*sympy.Identity(3)*m -( m_t - g1*s0*U + s0*g2*m0),
#          (m- m0)*S*(m - m0).T- (2*D/s0)*sympy.Identity(1),
#          ( P - V)*sympy.Identity(1) + (s0/(1+ s0*g2))*(m_t - m0 - (g1 *s0) *U)*S*U.T,]
eqns = [mu*W*u.T + V*sympy.Identity(1)  ,
        mu*W*mu.T - (2*e )* sympy.Identity(1),]
mu = sympy.solve(mu*W*u.T + V*sympy.Identity(1)  ,  mu, as_dict = False)
sympy.pprint(mu)

# 
# g2_ =s0*(m- m0)*S*(m - m0).T- (2*D)*sympy.eye(1)
# g1_ =( P - V)*sympy.Identity(1) + s0*(m-m0)*S*U.T


TypeError: First argument of MatrixElement should be a matrix

In [148]:
m_star = ( m_t + g1*s0*U + s0*g2*m0)/(1+s0*g2)



g1_star = solve(g1_.subs(m,m_star),  g1, as_dict = False)
sympy.pprint(g1_star)

g1_star_ = ((1+g2*s0)*(V-P)*sympy.eye(1) - s0* U * S* (m_t - m0).T)/(s0**2 *U*S*U.T)
eq = sympy.simplify(g2_.subs(m,m_star).subs(g1, g1_star_))
eq


⎧                                  P⋅g₂⋅s₀                                    
⎪g₁: - ─────────────────────────────────────────────────────────────── - ─────
⎨        2        2     2                 2                 2        2     2  
⎪      s₀ ⋅S₀₀⋅U₀₀  + s₀ ⋅S₀₁⋅U₀₀⋅U₀₁ + s₀ ⋅S₁₀⋅U₀₀⋅U₀₁ + s₀ ⋅S₁₁⋅U₀₁    s₀ ⋅S
⎩                                                                             

                          P                                                   
────────────────────────────────────────────────────────── + ─────────────────
      2     2                 2                 2        2     2        2     
₀₀⋅U₀₀  + s₀ ⋅S₀₁⋅U₀₀⋅U₀₁ + s₀ ⋅S₁₀⋅U₀₀⋅U₀₁ + s₀ ⋅S₁₁⋅U₀₁    s₀ ⋅S₀₀⋅U₀₀  + s₀
                                                                              

           V⋅g₂⋅s₀                                                            
────────────────────────────────────────────── + ─────────────────────────────
2                 2                 2        2    

s0*(-m0 + 1/(g2*s0 + 1)*((g2*s0)*m0 + (s0*((-s0)*U*S*(-m0.T + m_t.T) + Matrix([[-(P - V)*(g2*s0 + 1)]]))*(s0**2*U*S*U.T)**(-1))*U + m_t))*S*((1/(g2*s0 + 1)*((g2*s0)*m0 + (s0*((-s0)*U*S*(-m0.T + m_t.T) + Matrix([[-(P - V)*(g2*s0 + 1)]]))*(s0**2*U*S*U.T)**(-1))*U + m_t)).T - m0.T) + Matrix([[-2*D]])

In [150]:
g1_star_

((-s0)*U*S*(-m0.T + m_t.T) + Matrix([[(-P + V)*(g2*s0 + 1)]]))*(s0**2*U*S*U.T)**(-1)

In [142]:
g2_star = solve(eq,  g2, as_dict = False)

sympy.pprint(g2_star[0])

⎛                                                                             
⎜                2                                                           2
⎜- 4⋅D⋅s₀⋅S₀₀⋅U₀₀  - 4⋅D⋅s₀⋅S₀₁⋅U₀₀⋅U₀₁ - 4⋅D⋅s₀⋅S₁₀⋅U₀₀⋅U₀₁ - 4⋅D⋅s₀⋅S₁₁⋅U₀₁ 
⎜─────────────────────────────────────────────────────────────────────────────
⎜                                                                             
⎝                                                                             

                                                                              
      2                                                                       
 + 2⋅P  - 4⋅P⋅V - P⋅s₀⋅S₀₁⋅U₀₀⋅m₀ ₀₁ + P⋅s₀⋅S₀₁⋅U₀₀⋅mₜ ₀₁ + P⋅s₀⋅S₀₁⋅U₀₁⋅m₀ ₀₀
──────────────────────────────────────────────────────────────────────────────
                                                                              
                                                                              

                                                  

In [2]:
import numpy as np

In [103]:
values = np.array([1., 1., 5])
cons = np.array([[3, 1],[3, -1],[-5, 0]])
m0 = np.array([0,1])

In [18]:
x = np.dot( values, cons)/len(values)
covar = np.array([[.1, 0],[0, .01]])

target_cov_inv = np.linalg.inv(covar)

In [9]:
np.matmul(np.matmul(x,target_cov_inv),x)

401.1111111111111

In [22]:
print(x)
np.clip(x, a_min=np.array([-3, 1]), a_max=np.array([4,3]))

[-6.33333333  0.        ]


array([-3.,  1.])

In [28]:
u_bar = np.mean(m0-cons, axis=0)
np.matmul(np.matmul(u_bar,target_cov_inv),u_bar)

101.11111111111111

In [108]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [42]:
np.mean(np.sum(np.matmul(m0-cons, target_cov_inv)*(m0-cons), axis = 1))

array([ 90., 490., 350.])

In [56]:

class Buffer:

    def __init__(self, n_elements, max_buffer_size, reset_on_query):
        self.reset_on_query = reset_on_query
        self.max_buffer_size = max_buffer_size
        self.buffers = [list() for i in range(0, n_elements)]

    def update_buffer(self, datas):
        if isinstance(datas[0], list):
            for buffer, data in zip(self.buffers, datas):
                buffer.extend(data)
        else:
            for buffer, data in zip(self.buffers, datas):
                buffer.append(data)

        while len(self.buffers[0]) > self.max_buffer_size:
            for buffer in self.buffers:
                del buffer[0]

    def merge_buffer(self, addition_buffer):
        for buffer, addition in zip(self.buffers, addition_buffer.buffers):
            buffer +=addition

        while len(self.buffers[0]) > self.max_buffer_size:
            for buffer in self.buffers:
                del buffer[0]

    def read_buffer(self, reset=None):
        if reset is None:
            reset = self.reset_on_query

        res = tuple([buffer for buffer in self.buffers])

        if reset:
            for i in range(0, len(self.buffers)):
                self.buffers[i] = []

        return res

    def __len__(self):
        return len(self.buffers[0])





In [57]:
buffer_test = Buffer(n_elements=1, max_buffer_size = 10, reset_on_query = True)

In [11]:
import numpy as np

a = np.array([[1], [5], [4]])
1/a**2


array([[1.    ],
       [0.04  ],
       [0.0625]])

In [65]:
import numpy as np
EMPTY = BLACK = 0
WALL = GRAY = 1
TARGET = GREEN = 3
AGENT = RED = 4
SUCCESS = PINK = 6
COLORS = {BLACK: [0.0, 0.0, 0.0], GRAY: [0.5, 0.5, 0.5], GREEN: [0.0, 1.0, 0.0],
          RED: [1.0, 0.0, 0.0], PINK: [1.0, 0.0, 1.0]}

context = [2.5, .5]

size = [400, 300]
img_shape = [400, 400, 3]


def pos2pixel(pos ):
    return (400*(pos+4)/8).astype(np.uint16)

pos = context[0] + 4.
width = context[1]
ball_width =0.5*img_shape[0]/8
screen = np.zeros(img_shape)
print(screen.shape)


ml = pos2pixel(np.array([0,4]))

(400, 400, 3)


In [88]:
# self._viewer.line(np.array([3.9, 0.9]), np.array([4.1, 1.1]), color=(255, 0, 0), width=0.1)
# self._viewer.line(np.array([4.1, 0.9]), np.array([3.9, 1.1]), color=(255, 0, 0), width=0.1)
from skimage.draw import line_aa, rectangle, ellipse, disk
import matplotlib.pyplot as plt
img = np.ones((800, 800, 3), dtype=np.double)

rr, cc = rectangle(np.array([375, 0]), (425, 600))
img[rr, cc, 0] = 0
img[rr, cc, 1] = 0
img[rr, cc, 2] = 0

rr, cc = ellipse(r =700 ,c =400, r_radius= 80, c_radius = 8, rotation =45)
img[rr, cc, 0] = 1
img[rr, cc, 1] = 0
img[rr, cc, 2] = 0


rr, cc = ellipse(r =700 ,c =400, r_radius= 80, c_radius = 8, rotation =-45)
img[rr, cc, 0] = 1
img[rr, cc, 1] = 0
img[rr, cc, 2] = 0


center = np.array([100, 300])
rr, cc = disk(center.astype(int), 30, shape=img.shape)
img[rr,cc, :] = (.1,.1, .7)
x= img*255

In [1]:
import numpy as np
from utils.ma_policy_config import gen_ppo_distral_policy, dummy_policy_mapping_fn, policy_mapping_fn
from envs.wrappers import TimeLimitRewardWrapper
from envs.contextual_env import CtxDictWrapper, ctx_visibility, exp_group, DiscreteCtxDictWrapper
import itertools
from envs.gridworld_contextual import TaskSettableGridworld, coordinate_transform

size0 = (11, 11)
max_steps = 32
corridor0 = (1, 3)
embedding_map = [{0:(i,j),1:(9,9)} for i,j in itertools.product(range(1,10),range(1,4))]+\
                [{0:(i,j),1:(9,9)} for i,j in itertools.product(range(1,5),range(7,10))]
embedding_transform = [np.array([coordinate_transform(v[0], size0), coordinate_transform(v[1], size0)]) for v in embedding_map]
config0 = {'size': size0,
                        'corridor': corridor0,
                        'region': {0: (1, 1), 1: (-2, -2)}}  # 0 UL -> LR
ctx_mode = 1
embedding_dim = 4
embeddings = np.random.randn(len(embedding_map), embedding_dim)
env_creator = lambda config: DiscreteCtxDictWrapper(TimeLimitRewardWrapper(
    TaskSettableGridworld(config),max_episode_steps=max_steps, key = 'distance'),
    key='region', embedding_dim=embedding_dim, embedding_map= embedding_transform, embeddings = embeddings
    )

print(embedding_map)



[{0: (1, 1), 1: (9, 9)}, {0: (1, 2), 1: (9, 9)}, {0: (1, 3), 1: (9, 9)}, {0: (2, 1), 1: (9, 9)}, {0: (2, 2), 1: (9, 9)}, {0: (2, 3), 1: (9, 9)}, {0: (3, 1), 1: (9, 9)}, {0: (3, 2), 1: (9, 9)}, {0: (3, 3), 1: (9, 9)}, {0: (4, 1), 1: (9, 9)}, {0: (4, 2), 1: (9, 9)}, {0: (4, 3), 1: (9, 9)}, {0: (5, 1), 1: (9, 9)}, {0: (5, 2), 1: (9, 9)}, {0: (5, 3), 1: (9, 9)}, {0: (6, 1), 1: (9, 9)}, {0: (6, 2), 1: (9, 9)}, {0: (6, 3), 1: (9, 9)}, {0: (7, 1), 1: (9, 9)}, {0: (7, 2), 1: (9, 9)}, {0: (7, 3), 1: (9, 9)}, {0: (8, 1), 1: (9, 9)}, {0: (8, 2), 1: (9, 9)}, {0: (8, 3), 1: (9, 9)}, {0: (9, 1), 1: (9, 9)}, {0: (9, 2), 1: (9, 9)}, {0: (9, 3), 1: (9, 9)}, {0: (1, 7), 1: (9, 9)}, {0: (1, 8), 1: (9, 9)}, {0: (1, 9), 1: (9, 9)}, {0: (2, 7), 1: (9, 9)}, {0: (2, 8), 1: (9, 9)}, {0: (2, 9), 1: (9, 9)}, {0: (3, 7), 1: (9, 9)}, {0: (3, 8), 1: (9, 9)}, {0: (3, 9), 1: (9, 9)}, {0: (4, 7), 1: (9, 9)}, {0: (4, 8), 1: (9, 9)}, {0: (4, 9), 1: (9, 9)}]


In [2]:
env = env_creator(config0)

In [7]:
# print(env.get_task())
# embedding = np.array([ 1.24475707,  1.75301292, -0.51620965, -0.1485622])
# print(embeddings[10])
# print(embedding)
# env.set_task(embedding)
# print(env.get_task())
# print(sum((env.get_task()- embedding)**2))
# print(sum((embeddings[10]- embedding)**2))
#
env.reset()

(array([-0.23966942, -0.5       ]), {})

In [2]:
from envs.contextual_env import GMMCtxEnvWrapper, find_category_idx
import numpy as np

ctx_lb = -3*np.ones_like(embeddings[0])
ctx_ub = 3*np.ones_like(embeddings[0])

env_creator = lambda config: GMMCtxEnvWrapper(DiscreteCtxDictWrapper(TimeLimitRewardWrapper(
    TaskSettableGridworld(config0),max_episode_steps=max_steps, key = 'distance'),
    key='region', embedding_dim=embedding_dim, embedding_map= embedding_transform, embeddings = embeddings
    ), ctx_lb=ctx_lb, ctx_ub=ctx_ub, ctx_mode=ctx_mode, **config)

In [11]:
env_config = {'size': size0,
                        'corridor': corridor0,
                        'region': {0: (9, 1), 1: (9, 9)}}
# 0 UL -> LR
env_config_pars={'target_mean':  embeddings[find_category_idx(embedding_map, env_config['region']),:],
                        'target_var': np.square([.01, ]*embedding_dim),
                        'init_mean': np.zeros(embedding_dim),
                        'init_var': np.square([1, ]*embedding_dim),
                        'prior': None,
                 'curriculum': 'gaussian_self_paced',
                'kl_threshold' : 8000,
                'max_kl': 0.05,
                'perf_lb': -16,
                'std_lb':  np.square([.01, ]*embedding_dim)}

Traceback (most recent call last):
  File "/home/mohsen/.local/share/JetBrains/Toolbox/apps/PyCharm-P/ch-0/213.6777.50/plugins/python/helpers/pydev/_pydevd_bundle/pydevd_frame.py", line 861, in trace_dispatch
    result = plugin_manager.cmd_step_over(main_debugger, frame, event, self._args, stop_info, stop)
  File "/home/mohsen/.local/share/JetBrains/Toolbox/apps/PyCharm-P/ch-0/213.6777.50/plugins/python/helpers-pro/jupyter_debug/pydev_jupyter_plugin.py", line 144, in cmd_step_over
    if _is_inside_jupyter_cell(frame, pydb):
  File "/home/mohsen/.local/share/JetBrains/Toolbox/apps/PyCharm-P/ch-0/213.6777.50/plugins/python/helpers-pro/jupyter_debug/pydev_jupyter_plugin.py", line 209, in _is_inside_jupyter_cell
    if is_cell_filename(filename):
  File "/home/mohsen/.local/share/JetBrains/Toolbox/apps/PyCharm-P/ch-0/213.6777.50/plugins/python/helpers-pro/jupyter_debug/pydev_jupyter_plugin.py", line 220, in is_cell_filename
    ipython_shell = get_ipython()
NameError: name 'get_ipython' 

In [12]:
print(env_config_pars)
env = env_creator(env_config_pars)

In [24]:
a = np.array([2,1])
W = np.array([[.1, 0],[0,1]])

print(np.matmul(a,W,a.T))


UFuncTypeError: Cannot cast ufunc 'matmul' output from dtype('float64') to dtype('int64') with casting rule 'same_kind'

In [100]:
import numpy as np
target_cov_inv = np.array([[100, .2],[.2, 1]])
values_raw =np.array([0, 100, 0, 0]) 
theta = np.array([1, 3])
values = values_raw/values_raw.size
ctx_mean = np.array([1, 6, ])
contexts = np.array([[1, 6], [1, 0], [5, 6], [1,2]])
u_bar = (.5/values.size)*(np.dot(values,  np.matmul(ctx_mean - contexts, target_cov_inv) * (ctx_mean - contexts)))
W = np.diag(theta**-1.5 )@target_cov_inv@np.diag(theta**-.5)
# u_bar = np.mean(values*(np.matmul(ctx_mean - contexts, target_cov_inv) * (ctx_mean - contexts), axis=1))
# print(f'ctx_mean = \n{ctx_mean},\ncontexts = \n{contexts},\ntarget_cov_inv = \n{target_cov_inv}\n',
#       f'contexts - ctx_mean = \n{contexts - ctx_mean}\n',
#       f'target_cov_inv*(contexts - ctx_mean) = \n{np.matmul(ctx_mean - contexts, target_cov_inv)}\n',
#       f'omega = \n{np.matmul(ctx_mean - contexts, target_cov_inv)* (ctx_mean - contexts)}\n',
#       f'values = \n{values}\n',
#       f'values* omega = \n{.001*np.dot(values, np.matmul(ctx_mean - contexts, target_cov_inv)* (ctx_mean - contexts)).dot(target_cov_inv)}')
s1 = (ctx_mean - contexts)
s2 = s1@W
print ((ctx_mean - contexts).shape, W.shape)
s3 = s2*s1
u_bar = -.5*np.dot(s3.T, values)
print(f'W: {W.shape},\t W = {W}\n',
      f's1: {s1.shape},\t s1 = {s1}\n',
      f's2: {s2.shape},\t s2 = {s2}\n',
      f's3: {s3.shape},\t s3 = {s3}\n',
      f'u_bar: {u_bar.shape},\t u_bar = {u_bar},\t {W@u_bar.T} \n',
      f' u_bar_norm = {u_bar@W@u_bar.T}\n')
# print((ctx_mean - contexts)@W)
# print((((contexts - ctx_mean).T@(contexts - ctx_mean))@np.diag(theta**(-.5))@target_cov_inv@np.diag(theta**(-.5)))*np.eye(2))


(4, 2) (2, 2)
W: (2, 2),	 W = [[1.00000000e+02 1.15470054e-01]
 [3.84900179e-02 1.11111111e-01]]
 s1: (4, 2),	 s1 = [[ 0  0]
 [ 0  6]
 [-4  0]
 [ 0  4]]
 s2: (4, 2),	 s2 = [[ 0.00000000e+00  0.00000000e+00]
 [ 2.30940108e-01  6.66666667e-01]
 [-4.00000000e+02 -4.61880215e-01]
 [ 1.53960072e-01  4.44444444e-01]]
 s3: (4, 2),	 s3 = [[   0.            0.        ]
 [   0.            4.        ]
 [1600.           -0.        ]
 [   0.            1.77777778]]
 u_bar: (2,),	 u_bar = [ -0. -50.],	 [-5.77350269 -5.55555556] 
  u_bar_norm = 277.77777777777777



In [73]:
ctx_mean - contexts

array([[nan,  0.],
       [nan,  6.],
       [nan,  0.],
       [nan,  4.]])

In [71]:
A = np.array([[1,0],[.001, 0.01]])
x = np.array([[1, 0],])
np.fill_diagonal(A, np.clip(np.diag(A), a_min= 0.1, a_max= 0.8))
# print((A@x).shape)
print((x@A).shape)

(1, 2)


In [1]:
import numpy as np

In [6]:
a = np.array([[1,0],[0,2]])

np.invert(a)

array([[-2, -1],
       [-1, -3]])